# This is a basic workflow that is manually triggered to update the kodi plugin

name: Manual update

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Branch to run against'
        # Default value if no value is explicitly provided
        default: 'gh-actions-test'
        # Input has to be provided for the workflow to run
        required: true
      change_note1:
        description: 'Update 1'
 #       default: ''
        required: true
      change_note2:
        description: 'Update 2'
#        default: ''
        required: false
      change_note3:
        description: 'Update 3'
#        default: ''
        required: false
      change_note4:
        description: 'Update 4'
#        default: ''
        required: false
      change_note5:
        description: 'Update 5'
#        default: ''
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Build new version
      id: build
      shell: bash {0}
      env:
        notes[0]: ${{ github.event.inputs.change_note1 }}
        notes[1]: ${{ github.event.inputs.change_note2 }}
        notes[2]: ${{ github.event.inputs.change_note3 }}
        notes[3]: ${{ github.event.inputs.change_note4 }}
        notes[4]: ${{ github.event.inputs.change_note5 }}
      run: |
        cur_version=$(grep 'WatchNixtoons2" version' addon.xml | cut -f4 -d " " | cut -c 10- | cut -c -4)
        new_version=$(echo $cur_version | awk '{print $1+0.01}')
        if [[ ${{ github.event.inputs.branch }} == "master" ]]; then
          branch=""
        else
          branch=".${{ github.event.inputs.branch }}"
        fi
        sed -i "/toons2\" version\=\"/c\<addon id\=\"plugin.video.watchnixtoons2${branch}\" name\=\"WatchNixtoons2\" version\=\"${new_version}\" provider-name\=\"doko\/Christian-Haitian\">" addon.xml 
        mkdir plugin.video.watchnixtoons2${branch}
        sed -i "/Cartoons \&amp\; Anime/s//Cartoons \&amp\; Anime\n\n[B]${new_version}[\/B]/" addon.xml
        for note in $notes[0]
        do
          sed -i "/\[B\]$new_version\[\/B\]/s//\[B\]$new_version\[\/B\]\n- $note/" addon.xml
        done
        cp addon.xml Default.py *.jpg *.png plugin.video.watchnixtoons2${branch}/.
        cp -R Lib/ plugin.video.watchnixtoons2${branch}/
        cp -R resources/ plugin.video.watchnixtoons2${branch}/
        zip -9 -r ./plugin.video.watchnixtoons2${branch}-${new_version}.zip plugin.video.watchnixtoons2${branch}/
        rm -rf plugin.video.watchnixtoons2${branch}
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add plugin.video.watchnixtoons2${branch}-${new_version}.zip addon.xml
        git commit -m "Add plugin.video.watchnixtoons2${branch}-${new_version}.zip to repo"
#        echo "::set-output name=file::plugin.video.watchnixtoons2${branch}-${new_version}.zip"
    - uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.event.inputs.branch }}
